name: 'Hatchbox Deploy Action'
description: 'Send deployment notifications to the Hatchbox API'
branding:
  icon: 'globe'
  color: 'red'
inputs:
  deploy_key:
    description: 'Your Hatchbox.io app's Deploy Key.'
    required: true
  sha:
    description: 'The commit sha to be deployed.'
    required: false
    default: ${{ github.sha }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.deploy_key }}
    - ${{ inputs.sha }}