name: 'Hatchbox Deploy Action'
description: 'Send deployment notifications to the Hatchbox API'
branding:
  icon: 'globe'
  color: 'red'
inputs:
  deploy_key:
    description: 'Your Hatchbox.io app's Deploy Key.'
    required: true
  sha:
    description: 'The commit sha to be deployed.'
    required: false
    default: ${{ github.sha }}
  branch:
    description: 'The branch that needs to be deployed'
    required: false
    default: 'main'
  classic:
    description: 'If hatchbox classic is used'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.deploy_key }}
    - ${{ inputs.sha }}
    - ${{ inputs.branch }}
    - ${{ inputs.classic }}